[package]
name = "save"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
glob = "0.3.3"
humantime-serde = "1.1.1"
reqwest = { version = "0.12.24", features = ["blocking"] }
serde = "1.0.228"
serde_json = "1.0.145"
toml = "0.9.8"
which = "8.0.0"
